const assert=require('node:assert/strict');const {scan}=require('./palette-support.cjs');
module.exports=async page=>{
 await page.goto('http://127.0.0.1:4173/gestao?sec=dados',{waitUntil:'networkidle'});await scan(page,'F14 dados vazio');
 const photo = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j2ioAAAAASUVORK5CYII=';
 await page.evaluate(async base64 => {
  const bytes=Uint8Array.from(atob(base64),char=>char.charCodeAt(0));
  const db=await new Promise((resolve,reject)=>{const req=indexedDB.open('mercadinho-product-photos',1);req.onupgradeneeded=()=>req.result.createObjectStore('photos');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});
  await new Promise((resolve,reject)=>{const tx=db.transaction('photos','readwrite');tx.objectStore('photos').put(new Blob([bytes],{type:'image/png'}),'fixture-photo');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});db.close();
  const saved=JSON.parse(localStorage.getItem('pdv-mercado'));saved.state.products['123'].photoId='fixture-photo';saved.state.revision++;localStorage.setItem('pdv-mercado',JSON.stringify(saved));
 },photo);await page.reload({waitUntil:'networkidle'});
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Exportar backup com fotos',exact:true}).click();const download=await downloadPromise;const stream=await download.createReadStream();const chunks=[];for await(const chunk of stream)chunks.push(chunk);const backup=Buffer.concat(chunks);const saved=JSON.parse(backup);assert.equal(saved.version,1);assert.equal(saved.payload.data.products['123'].barcode,'123');assert.equal(saved.payload.data.staff,undefined);assert.equal(saved.payload.photos['fixture-photo'],`data:image/png;base64,${photo}`);
 await page.getByLabel('Conferir CSV de produtos',{exact:false}).setInputFiles({name:'bad.csv',mimeType:'text/csv',buffer:Buffer.from('codigo;nome;preco;estoque\n001;A;10;2\n001;B;11;3\n')});await page.getByText('Linha 3: confira código, nome, valores e duplicação.',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Importar produtos',exact:true}).isDisabled(),true);await scan(page,'F14 CSV inválido');
 await page.getByLabel('Conferir CSV de produtos',{exact:false}).setInputFiles({name:'valid.csv',mimeType:'text/csv',buffer:Buffer.from('codigo;nome;preco;estoque;custo;minimo;unidade\n001;Feijão;10,00;12;7,00;8;un\n')});await page.getByRole('button',{name:'Importar produtos',exact:true}).click();await page.getByRole('alertdialog').getByRole('button',{name:'Importar produtos',exact:true}).click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('pdv-mercado')).state.products['001']?.stock===12);
 await page.getByLabel('Escolher backup para conferir (até 50 MB)',{exact:false}).setInputFiles({name:'backup.json',mimeType:'application/json',buffer:backup});await page.getByRole('heading',{name:'Prévia da restauração',exact:true}).waitFor();assert.equal(await page.evaluate(()=>Object.keys(JSON.parse(localStorage.getItem('pdv-mercado')).state.products).length),2);await page.getByRole('button',{name:'Restaurar backup',exact:true}).click();await page.getByRole('alertdialog').getByRole('button',{name:'Restaurar backup',exact:true}).click();await page.waitForFunction(()=>Object.keys(JSON.parse(localStorage.getItem('pdv-mercado')).state.products).length===1);assert.ok(await page.evaluate(()=>localStorage.getItem('pdv-before-restore')));await scan(page,'F14 restauração');
 const restored=await page.evaluate(async()=>{const id=JSON.parse(localStorage.getItem('pdv-mercado')).state.products['123'].photoId;const db=await new Promise((resolve,reject)=>{const req=indexedDB.open('mercadinho-product-photos',1);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});const blob=await new Promise((resolve,reject)=>{const req=db.transaction('photos','readonly').objectStore('photos').get(id);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});db.close();return {id,base64:btoa(String.fromCharCode(...new Uint8Array(await blob.arrayBuffer())))};});assert.notEqual(restored.id,'fixture-photo');assert.equal(restored.base64,photo);
 saved.payload.data.products['123'].stock=999;await page.getByLabel('Escolher backup para conferir (até 50 MB)',{exact:false}).setInputFiles({name:'corrupt.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(saved))});await page.getByRole('alert').filter({hasText:'integridade inválida'}).waitFor();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('pdv-mercado')).state.products['123'].stock),2);return 7;
};
