const assert=require('node:assert/strict');
const {scan}=require('./palette-support.cjs');
const read=page=>page.evaluate(()=>JSON.parse(localStorage.getItem('pdv-mercado')).state);
module.exports=async page=>{
 await page.goto('http://127.0.0.1:4173/gestao?sec=fornecedores',{waitUntil:'networkidle'});
 await page.getByLabel('Nome do fornecedor',{exact:true}).fill('Distribuidora União 🛒');await page.getByLabel('Contato (opcional)',{exact:true}).fill('Contato de teste');await page.getByRole('button',{name:'Salvar fornecedor',exact:true}).click();await page.getByRole('heading',{name:'Distribuidora União 🛒',exact:true}).waitFor();await scan(page,'F09 fornecedores');
 await page.goto('http://127.0.0.1:4173/gestao?sec=recebimentos',{waitUntil:'networkidle'});
 const state=await read(page);await page.getByLabel('Fornecedor',{exact:true}).selectOption(state.suppliers[0].id);await page.getByLabel('Produto recebido 1',{exact:true}).selectOption('123');await page.getByLabel('Embalagens 1',{exact:true}).fill('2');await page.getByLabel('Unidades por embalagem 1',{exact:true}).fill('12');await page.getByLabel('Custo da embalagem 1 (R$)',{exact:true}).fill('36');await page.getByLabel('Lote 1 (opcional)',{exact:true}).fill('Lote A');await page.getByLabel('Validade 1 (opcional)',{exact:true}).fill('2099-01-01');await scan(page,'F09 recebimento preenchido');await page.getByRole('button',{name:'Registrar recebimento',exact:true}).dblclick();
 await page.waitForFunction(()=>JSON.parse(localStorage.getItem('pdv-mercado')).state.receivings.length===1);const result=await read(page);assert.equal(result.products['123'].stock,26);assert.equal(result.receivings[0].total,72);assert.equal(result.lots[0].available,24);await scan(page,'F09 recebimento confirmado');
 await page.goto('http://127.0.0.1:4173/gestao?sec=movimentos',{waitUntil:'networkidle'});await page.getByLabel('Produto do ajuste',{exact:true}).selectOption('123');await page.getByLabel('Tipo de ajuste',{exact:true}).selectOption('loss');await page.getByLabel('Quantidade do ajuste',{exact:true}).fill('1');await page.getByLabel('Motivo do ajuste',{exact:true}).fill('Embalagem avariada');await page.getByRole('button',{name:'Registrar ajuste',exact:true}).click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('pdv-mercado')).state.products['123'].stock===25);await page.getByRole('button',{name:'Registrar ajuste',exact:true}).click();await page.getByRole('alert').filter({hasText:'Preencha os campos'}).waitFor();assert.equal((await read(page)).products['123'].stock,25);await scan(page,'F06 perda e erro');
 await page.getByRole('link',{name:'Estoque',exact:true}).click();await page.getByRole('button',{name:/Arroz São João/}).click();
 const editor=page.getByRole('dialog',{name:'Editar produto',exact:true});await editor.getByText('Gestão do produto (opcional)',{exact:true}).click();
 const cost=editor.getByLabel('Custo unitário (R$; vazio = não informado)',{exact:true});await cost.fill('');await cost.pressSequentially('7,50');assert.equal(await cost.inputValue(),'7,50');await editor.getByRole('button',{name:'Atualizar produto',exact:true}).click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('pdv-mercado')).state.products['123'].cost===7.5);await scan(page,'F06 custo decimal preservado');
 return 7;
};
