/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as MaisRouteImport } from './routes/mais'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as VenderRouteImport } from './routes/vender'
import { Route as VendasIndexRouteImport } from './routes/vendas.index'
import { Route as VendasConfiguracoesRouteImport } from './routes/vendas.configuracoes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const MaisRoute = MaisRouteImport.update({
  id: '/mais',
  path: '/mais',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const VenderRoute = VenderRouteImport.update({
  id: '/vender',
  path: '/vender',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasIndexRoute = VendasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendasRoute,
} as any)
const VendasConfiguracoesRoute = VendasConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => VendasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/estoque': typeof EstoqueRoute
  '/mais': typeof MaisRoute
  '/vendas': typeof VendasRouteWithChildren
  '/vender': typeof VenderRoute
  '/vendas/configuracoes': typeof VendasConfiguracoesRoute
  '/vendas/': typeof VendasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/estoque': typeof EstoqueRoute
  '/mais': typeof MaisRoute
  '/vender': typeof VenderRoute
  '/vendas/configuracoes': typeof VendasConfiguracoesRoute
  '/vendas': typeof VendasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/estoque': typeof EstoqueRoute
  '/mais': typeof MaisRoute
  '/vendas': typeof VendasRouteWithChildren
  '/vender': typeof VenderRoute
  '/vendas/configuracoes': typeof VendasConfiguracoesRoute
  '/vendas/': typeof VendasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/estoque'
    | '/mais'
    | '/vendas'
    | '/vender'
    | '/vendas/configuracoes'
    | '/vendas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/estoque' | '/mais' | '/vender' | '/vendas/configuracoes' | '/vendas'
  id:
    | '__root__'
    | '/'
    | '/estoque'
    | '/mais'
    | '/vendas'
    | '/vender'
    | '/vendas/configuracoes'
    | '/vendas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EstoqueRoute: typeof EstoqueRoute
  MaisRoute: typeof MaisRoute
  VendasRoute: typeof VendasRouteWithChildren
  VenderRoute: typeof VenderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mais': {
      id: '/mais'
      path: '/mais'
      fullPath: '/mais'
      preLoaderRoute: typeof MaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vender': {
      id: '/vender'
      path: '/vender'
      fullPath: '/vender'
      preLoaderRoute: typeof VenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas/': {
      id: '/vendas/'
      path: '/'
      fullPath: '/vendas/'
      preLoaderRoute: typeof VendasIndexRouteImport
      parentRoute: typeof VendasRoute
    }
    '/vendas/configuracoes': {
      id: '/vendas/configuracoes'
      path: '/configuracoes'
      fullPath: '/vendas/configuracoes'
      preLoaderRoute: typeof VendasConfiguracoesRouteImport
      parentRoute: typeof VendasRoute
    }
  }
}

interface VendasRouteChildren {
  VendasConfiguracoesRoute: typeof VendasConfiguracoesRoute
  VendasIndexRoute: typeof VendasIndexRoute
}

const VendasRouteChildren: VendasRouteChildren = {
  VendasConfiguracoesRoute: VendasConfiguracoesRoute,
  VendasIndexRoute: VendasIndexRoute,
}

const VendasRouteWithChildren =
  VendasRoute._addFileChildren(VendasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EstoqueRoute: EstoqueRoute,
  MaisRoute: MaisRoute,
  VendasRoute: VendasRouteWithChildren,
  VenderRoute: VenderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
